---
version: "2"
services:
  homer:
    # image: b4bz/homer
    #To build from source, comment previous line and uncomment below
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: homerun
    volumes:
      - /your/local/assets/:/www/assets
    ports:
      - 1111:8080
    #environment:
    #  - UID=1000
    #  - GID=1000
    restart: unless-stopped
